name: CI
on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/ci.yml'
    - '**.rs'
    - '**.toml'
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - '**.rs'
    - '**.toml'
jobs:
  test-and-check:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install bundletool
        run: |
          wget https://github.com/google/bundletool/releases/download/1.8.2/bundletool-all-1.8.2.jar
          mv bundletool-all-1.8.2.jar $HOME/bundletool.jar
      - name: Check the format
        run: cargo +nightly fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::upper_case_acronyms
      - name: Run tests
        run: |
          export BUNDLETOOL_PATH="$HOME/bundletool.jar"
          set --export ANDROID_HOME $HOME/Android/Sdk
          set -gx PATH $ANDROID_HOME/emulator $PATH;
          set -gx PATH $ANDROID_HOME/tools $PATH;
          set -gx PATH $ANDROID_HOME/tools/bin $PATH;
          cargo test --no-fail-fast
      - name: Check for deadlinks
        run: |
          cargo install cargo-deadlinks
          cargo deadlinks --check-http || true
